export const pageData = [
  {
    id: "lemon-image",
    title: "Lemon Soda",
    url: "/lemon-soda.jpg",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://lemonsoda.it/special-edition/",
  },
  {
    id: "remax-image",
    title: "REMAX",
    url: "/ideology-website-mobile-11.png",
    info: ["UI/UX", "DEVELOPMENT", "2020"],
    page: "https://www.remax-primaclasse.it/",
  },
  {
    id: "ideology-image",
    title: "ideology",
    url: "/ideology-website-mobile-7.jpg",
    info: ["UI/UX", "DEVELOPMENT", "2020"],
    page: "https://www.ideology.it/",
  },
  {
    id: "mabu-image",
    title: "mabù",
    url: "/ideology-website-mobile-4.jpg",
    info: ["UI/UX", "DEVELOPMENT", "2020"],
    page: "https://www.mabuprofumerie.it/",
  },
  {
    id: "bionatur-image",
    title: "bionatur",
    url: "/ideology-website-mobile-6.jpg",
    info: ["UI/UX", "DEVELOPMENT", "2020"],
    page: "https://www.bionatursrl.com/",
  },
  {
    id: "base-image",
    title: "medical space",
    url: "/ideology-website-mobile-9.png",
    info: ["UI/UX", "DEVELOPMENT", "2020"],
    page: "https://www.medicalspace.it/",
  },
  {
    id: "negozio-image",
    title: "n. d. frutta",
    url: "/ideology-website-mobile-10.png",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://www.negoziodellafrutta.it/",
  },
  {
    id: "area-image",
    title: "area system",
    url: "/ideology-website-mobile-12.png",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://www.areasystem.it/",
  },
  {
    id: "mizzica-image",
    title: "mizzica",
    url: "/ideology-website-mobile-13.png",
    info: ["DEVELOPMENT", "2021"],
    page: "https://www.mizzicaristorante.it/",
  },
  {
    id: "ops-image",
    title: "o.p.s.",
    url: "/ideology-website-mobile-14.png",
    info: ["DEVELOPMENT", "2021"],
    page: "https://www.onlypistachioselected.com/",
  },

  {
    id: "bottone-image",
    title: "bottone",
    url: "/ideology-website-mobile-15.png",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://www.bottonecannoli.it/",
  },
  {
    id: "v-lex-image",
    title: "v-lex",
    url: "/ideology-website-mobile-16.png",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://www.v-lex.it/",
  },
  {
    id: "rapinzeri-image",
    title: "rapinzeri",
    url: "/ideology-website-mobile-19.png",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://www.rapinzeri.it/",
  },
  {
    id: "viagiatori-image",
    title: "viagiatori",
    url: "/ideology-website-mobile-18.png",
    info: ["UI/UX", "DEVELOPMENT", "2021"],
    page: "https://www.viagiatori-schinina.com/",
  },
  {
    id: "elettrico-image",
    title: "n.elettrico",
    url: "/ideology-website-mobile-17.png",
    info: ["UI/UX", "DEVELOPMENT", "2022"],
    page: "https://www.noleggioelettrico.com/",
  },
];
